### ISSUE TITLE
Define policy for the asset-store and admin rights in Girder

### ISSUE THREAD

**Issue by aashish24** [OpenGeoscience/database_assetstore#31]
@jbeezley @zachmullen and @dorukozturk  may be interested in helping out with defining the policies that makes most sense for the project and for the Girder. 

@manthey is planning on creating a google document.

**Comment by manthey** [comment]
There is a Google doc.

I think the simplest way to handle this is to have a special `assetstoreId` value that is stored in a file to indicate that it uses the generalized database assetstore interface, rather than a specific assetstore.  The file's `DB_INFO_KEY` dictionary would include the database connection information (the uri) rather than getting it from a specific assetstore.  The database uri is sufficient; we glean the type from the protocol and the extra db parameters can be included as part of the query parameters.

**Comment by manthey** [comment]
This is being subsumed into issue #43.  The acls that are mentioned there will determine how users can create database files.
